### ISSUE TITLE
Problems during the training phase of the model

### ISSUE THREAD

**Issue by 13265170340** [srvk/eesen#182]
Traceback (most recent call last):
  File "utils/prep_ctc_trans.py", line 75, in <module>
    out_line += dict[unk_word] + ' '
KeyError: '<UNK>'
Traceback (most recent call last):
  File "utils/prep_ctc_trans.py", line 75, in <module>
    out_line += dict[unk_word] + ' '
KeyError: '<UNK>'

**Comment by fmetze** [comment]
I believe this means that you have an invalid entry in your dictionary or your vocabulary somewhere. Please check.

**Comment by 13265170340** [comment]
@fmetze Thank you for your answer, I will take a closer look
